### ISSUE TITLE
可以提供跨语言伪数据（Cross-Lingual Pseudo Data）这份数据集吗？

### ISSUE THREAD

**Issue by Banner-Z** [blcuicall/mcts#1]
您好，非常感谢您在中文文本简化中的贡献！看上去跨语言伪数据（Cross-Lingual Pseudo Data）是一份相对有效的训练集，请问是否可以共享这份数据？

**Comment by chongruining** [comment]
感谢您对我们工作的关注！我们已经在最近一次更新中对跨语言伪数据（Cross-Lingual Pseudo Data）进行了开源，您可以在 pseudo_data 目录下访问到它们。

**Comment by Banner-Z** [comment]
Thanks a lot!
